# Generated by Django 5.0 on 2023-12-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_registration_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
