# Generated by Django 5.0 on 2024-01-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_refer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(default=0, max_length=50, null=True, unique=True),
        ),
    ]
