# Generated by Django 5.0 on 2023-12-27 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancard', models.CharField(max_length=100, unique=True)),
                ('aadharcard', models.CharField(max_length=100, unique=True)),
                ('account_no', models.CharField(max_length=100, unique=True)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
