# Generated by Django 5.0 on 2023-12-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_kycdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetails',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
