# Generated by Django 5.0 on 2024-01-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_refer_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_by_refer',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
