# Generated by Django 5.0 on 2023-12-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_user_user_name_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_above18',
            field=models.BooleanField(default=False),
        ),
    ]
