# Generated by Django 5.0 on 2023-12-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refer_code',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
