# Generated by Django 5.0 on 2024-01-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_addlanguage_timelimite_carddetail_setcashlimit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refer_code',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
    ]
